name: Rotate Keys

on:
  schedule:
    - cron: "0 0 */3 * *"
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: node generate_keys.js

      - run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add keys.json
          git commit -m "Auto rotate 500 keys"
          git push
